Testing another detect configuration

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,7 +2,9 @@
 # bin/detect <build-dir>
 
 if [ -f $1/config/kong.conf.etlua ]; then
-  echo "Kong" && exit 0
-else
-  echo "no" && exit 1
+  echo 'Detected Kong config'
+  exit 0
 fi
+
+>&2 echo 'Kong: config/kong.conf.etlua not found in application root'
+exit 1
